// <auto-generated />
using System;
using Fiap.Api.Donation1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Donation1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231011215807_ProdutoDataIndex")]
    partial class ProdutoDataIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Donation1.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SugestaoTroca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("DataCadastro");

                    b.HasIndex("TipoProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4426),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4427),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 1",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 2,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4443),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4444),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 2",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 3,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4446),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4446),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 3",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 4,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4448),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4448),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 4",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 5,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4450),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4450),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 5",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 6,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4452),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4452),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 6",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 7,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4456),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4457),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 7",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 8,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4458),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4458),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 8",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 9,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4460),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4460),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 9",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 10,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4466),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4466),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 10",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 11,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4468),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4468),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 11",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 12,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4469),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4470),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 12",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 13,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4471),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4471),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 13",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 14,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4472),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4473),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 14",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 15,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4474),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4474),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 15",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 16,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4475),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4476),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 16",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 17,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4477),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4478),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 17",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 18,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4479),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4479),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 18",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 19,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4481),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4481),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 19",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 20,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4482),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4483),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 20",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 21,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4484),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4484),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 21",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 22,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4486),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4486),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 22",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 23,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4487),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4488),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 23",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 24,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4489),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4489),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 24",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 25,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4490),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4491),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 25",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 26,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4492),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4492),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 26",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 27,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4494),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4494),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 27",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 28,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4495),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4495),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 28",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 29,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4497),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4497),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 29",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 30,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4498),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4498),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 30",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 31,
                            DataCadastro = new DateTime(2023, 10, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4644),
                            DataExpiracao = new DateTime(2025, 4, 11, 18, 58, 7, 720, DateTimeKind.Local).AddTicks(4644),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 31",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.TipoProdutoModel", b =>
                {
                    b.Property<int>("TipoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoProdutoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("TipoProdutoId");

                    b.ToTable("TipoProduto");

                    b.HasData(
                        new
                        {
                            TipoProdutoId = 1,
                            Descricao = "Descrição para celular",
                            Nome = "Celular"
                        },
                        new
                        {
                            TipoProdutoId = 2,
                            Descricao = "Descrição para TV",
                            Nome = "TVs"
                        },
                        new
                        {
                            TipoProdutoId = 3,
                            Descricao = "Descrição para ar-condicionado",
                            Nome = "Ar-condicionado"
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            EmailUsuario = "sa@fiap.com.br",
                            NomeUsuario = "Super Admin",
                            Regra = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            UsuarioId = 2,
                            EmailUsuario = "fmoreni@fiap.com.br",
                            NomeUsuario = "Flavio Moreni",
                            Regra = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            UsuarioId = 3,
                            EmailUsuario = "emoreni@fiap.com.br",
                            NomeUsuario = "Eduardo Moreni",
                            Regra = "admin",
                            Senha = "123456"
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.ProdutoModel", b =>
                {
                    b.HasOne("Fiap.Api.Donation1.Models.TipoProdutoModel", "TipoProduto")
                        .WithMany()
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.Donation1.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProduto");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
